# -*- coding: utf-8 -*-
"""Stack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QD9k2z22pCgECy-SKOJsIYJUrQqZU0og
"""

class Stack:
  def __init__(self):
    self.arrays = []

  def push(self,contain):
    self.arrays.append(contain)
    
  def pop(self):
    if not self.isEmpty():
      self.arrays.pop()
      return
    return "Stack Kosong"

  def isEmpty(self):
    return self.arrays == []

  def peek(self):
    if not self.isEmpty():
      return self.arrays[len(self.arrays)-1]
    return "Stack Kosong"
    
  def display(self):
    print(self.arrays)

s = Stack()

s.push(1)
s.push(2)
s.push(3)
s.push(4)

s.display()

s.pop()

s.display()

s.peek()

s.isEmpty()

s.pop()
s.pop()
s.pop()

s.peek()

s.isEmpty()

s.pop()