# -*- coding: utf-8 -*-
"""doubleLinkedList.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CY79S13Xjad_Q6HOyA7QL7dwuUjp_Eaf
"""

class Node:
  next = None
  back = None
  data = None

class DLinkedList:
  def __init__(self):
    self.head = None
    self.tail = None

  def add(self,data):
    lists = Node()
    lists.data = data
    if self.head == None:
      self.head = lists
      self.tail = lists
      
    else :
      lastList = self.tail
      lastList.next = lists
      lists.back = lastList
      self.tail = lists

  def delete(self,data):
    """delete first data that match"""
    temp = self.head
    if self.head.data == data:
      self.head = self.head.next
      self.head.back = None
      print("data {} has been removed".format(data))
      return

    pointerCurrent = self.head.next  
    while pointerCurrent != None:
      if pointerCurrent.data == data:
        before = pointerCurrent.back
        after = pointerCurrent.next
        if pointerCurrent.data == self.tail.data:
          self.tail = before
          before.next = None
        else :
          before.next = after
          after.back = before
        print("data {} has been removed".format(data))
        return
      pointerCurrent = pointerCurrent.next

    print("There is no data {} in list, use method prints to see the list".format(data))

  def prints(self):
    temp = self.head
    IsTail = False
    while temp != None:
      before = temp.back.data if temp.back!= None else None
      after = temp.next.data if temp.next != None else None
      print(before,
            temp.data,
            after)
      temp = temp.next

singular = DLinkedList()
singular.add(1)

singular.add(2)

singular.add(3)
singular.add(4)

singular.prints()

singular.delete(3)

singular.prints()

singular.delete(5)

singular.prints()

singular.delete(1)

singular.prints()

singular.head.data

singular.tail.data

singular.delete(4)

singular.prints()

singular.head.data

singular.tail.data